// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteBomTrato.Data;

namespace TesteBomTrato.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210425184656_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("TesteBomTrato.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Escritorio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeReclamante")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroProcesso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValorCausa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Processos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Escritorio = "Guttenber",
                            NomeReclamante = "Kevin",
                            NumeroProcesso = 1,
                            ValorCausa = "1500,00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
