// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteBomTrato.Data;

namespace TesteBomTrato.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteBomTrato.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Escritorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeReclamante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroProcesso")
                        .HasColumnType("int");

                    b.Property<string>("ValorCausa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Escritorio = "LalaLand",
                            NomeReclamante = "Kevin",
                            NumeroProcesso = 1,
                            ValorCausa = "1500"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
